language: ruby
rvm:
  - 2.1.1
  - 2.1.2
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
env:
  - CI=true
gemfile:
    - Gemfile
branches:
    only:
        - master
before_install:
      - gem update --system
install: "bundle install"
#script: "bundle exec rake spec:unit spec:acceptance features"
script "bundle exec rake"
